/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veriyapilariproje2;

import java.io.BufferedReader;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel; 
import javax.swing.JFileChooser;

import javax.swing.JOptionPane;

/*
 * @file veriyapilari_2 KuyrukEkrani.java
 * @description bu frame'de kuyruk yapısının görüntülenmesini, önceliğe göre çağrılmasını sağlayan ve aynı zamanda kuyruk yapısı üzerinde
 bazı işlemleri yapmamızı sağlayan swing ekranı yer almaktadır. Ekran üzerinde yer alan butonlar, listede yer alan müşterileri listeleme,
 listeden öncelik sırasına göre çıkan müşterileri listeleme, toplam sure görüntüleme, toplam fatura goruntuleme, 
 girilen verilerle istenen bilgileri görüntüleme gibi işlemleri yapmaktadır.
 * @assignment Proje 2  
 * @date  20/12/2019 - 21/12/2019 - 22/12/2019
 * @author Emre USTA   emreustaa34@gmail.com
 */
public class KuyrukEkrani extends javax.swing.JFrame {

    /**
     * Creates new form KuyrukEkrani
     */
    QueueList queueList = new QueueList();
    int toplamZaman = 0;
    double toplamFaturaTutari = 0;
    File dosya;
    String path = null;
    BufferedReader reader = null;
    DefaultListModel dlmMusteriler = new DefaultListModel();
    DefaultListModel dlmKuyruk = new DefaultListModel();
    DefaultListModel dlmSonuc = new DefaultListModel();

    public KuyrukEkrani() {
        initComponents();
        setTitle("Kuyruk Ekrani");
        setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDosyaOku = new javax.swing.JButton();
        lblMusteriler = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listKuyruktanCikanlar = new javax.swing.JList<>();
        btnMusteriCagir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listMusteriler = new javax.swing.JList<>();
        btnToplamSure = new javax.swing.JButton();
        btnToplamFatura = new javax.swing.JButton();
        btnOncelikGir = new javax.swing.JButton();
        txtOncelikGir = new javax.swing.JTextField();
        btnOncelikToplamSure = new javax.swing.JButton();
        txtOncelikToplamSure = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstSonuc = new javax.swing.JList<>();
        btnFaturaGir = new javax.swing.JButton();
        txtFaturaGir = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDosyaOku.setText("Dosya Oku");
        btnDosyaOku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosyaOkuActionPerformed(evt);
            }
        });

        lblMusteriler.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblMusteriler.setText("Musteriler Listesi");

        jScrollPane1.setViewportView(listKuyruktanCikanlar);

        btnMusteriCagir.setText("Musteri Cagir");
        btnMusteriCagir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMusteriCagirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Kuyruktan Cikan Musteriler");

        jScrollPane2.setViewportView(listMusteriler);

        btnToplamSure.setText("Toplam Sure");
        btnToplamSure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToplamSureActionPerformed(evt);
            }
        });

        btnToplamFatura.setText("Toplam Fatura");
        btnToplamFatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToplamFaturaActionPerformed(evt);
            }
        });

        btnOncelikGir.setText("Oncelik Gir");
        btnOncelikGir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOncelikGirActionPerformed(evt);
            }
        });

        btnOncelikToplamSure.setText("Oncelik Toplam Sure");
        btnOncelikToplamSure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOncelikToplamSureActionPerformed(evt);
            }
        });

        jLabel2.setText("Sonuc ");

        jScrollPane3.setViewportView(lstSonuc);

        btnFaturaGir.setText("Fatura Gir");
        btnFaturaGir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFaturaGirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDosyaOku)
                    .addComponent(lblMusteriler)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMusteriCagir)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnToplamSure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOncelikGir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOncelikToplamSure)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtOncelikToplamSure, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnToplamFatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtOncelikGir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtFaturaGir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFaturaGir, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDosyaOku)
                    .addComponent(btnMusteriCagir)
                    .addComponent(btnToplamSure)
                    .addComponent(btnToplamFatura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOncelikGir)
                            .addComponent(txtOncelikGir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOncelikToplamSure)
                            .addComponent(txtOncelikToplamSure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnFaturaGir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFaturaGir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(135, 135, 135))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3)
                                .addGap(17, 17, 17))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMusteriler)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap(83, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDosyaOkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosyaOkuActionPerformed
        // TODO add your handling code here:
        //node = new Node();
        dosya = null;
        String path = null;
        JOptionPane x = new JOptionPane();
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(fileChooser);
        dosya = fileChooser.getSelectedFile();
        path = dosya.getAbsolutePath();

        try {

            reader = new BufferedReader(new FileReader(dosya));
            String satir = reader.readLine();

            while (satir != null) {

                String kelime[] = satir.split("#");
                dlmMusteriler.addElement(satir);

                queueList.enqueue(kelime[0], kelime[1], Double.valueOf(kelime[2]), Integer.valueOf(kelime[3]), Integer.valueOf(kelime[4]));

                satir = reader.readLine();
                toplamZaman += Integer.valueOf(kelime[4]);
                toplamFaturaTutari += Double.valueOf(kelime[2]);

            }
            queueList.printList();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(KuyrukEkrani.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(KuyrukEkrani.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                reader.close();
            } catch (IOException ex) {
                Logger.getLogger(KuyrukEkrani.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        listMusteriler.setModel(dlmMusteriler);


    }//GEN-LAST:event_btnDosyaOkuActionPerformed

    private void btnMusteriCagirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMusteriCagirActionPerformed

        System.out.println("After Dequeue");

        dlmKuyruk.addElement(queueList.dequeue());
        queueList.printList();

        listKuyruktanCikanlar.setModel(dlmKuyruk);


    }//GEN-LAST:event_btnMusteriCagirActionPerformed

    private void btnToplamSureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToplamSureActionPerformed
        // TODO add your handling code here:
        dlmSonuc.removeAllElements();
        if (queueList.front == null) {
            dlmSonuc.addElement("Gecen toplam zaman:  " + toplamZaman);

        } else {
            dlmSonuc.addElement("Kuyruk hala dolu");
        }
        lstSonuc.setModel(dlmSonuc);
    }//GEN-LAST:event_btnToplamSureActionPerformed

    private void btnToplamFaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToplamFaturaActionPerformed
        dlmSonuc.removeAllElements();
        if (queueList.front == null) {
            dlmSonuc.addElement("Toplam Fatura Miktari : " + queueList.fatura);
            dlmSonuc.addElement("Toplam Fatura Tutari : " + toplamFaturaTutari);

        } else {
            dlmSonuc.addElement("Kuyruk hala dolu");

        }

        lstSonuc.setModel(dlmSonuc);
    }//GEN-LAST:event_btnToplamFaturaActionPerformed

    private void btnOncelikGirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOncelikGirActionPerformed
        // TODO add your handling code here:
        dlmSonuc.removeAllElements();
        try {
            Node oncelik = queueList.front;

            int kacinci = 1;
            while (oncelik != null) {
                if (oncelik.oncelik == Integer.valueOf(txtOncelikGir.getText())) {
                    dlmSonuc.addElement(oncelik.adSoyad + " müsterisi " + kacinci + " sirada.");

                }
                kacinci++;
                oncelik = oncelik.next;
            }
            lstSonuc.setModel(dlmSonuc);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Hatali giris yaptiniz ,hataniz : " + e);

        }


    }//GEN-LAST:event_btnOncelikGirActionPerformed

    private void btnOncelikToplamSureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOncelikToplamSureActionPerformed
        // TODO add your handling code here:
        dlmSonuc.removeAllElements();
        try {
            Node oncelikToplam = queueList.front;
            int toplamOncelik = 0;

            while (oncelikToplam != null) {

                if (oncelikToplam.oncelik == Integer.valueOf(txtOncelikToplamSure.getText())) {
                    toplamOncelik += oncelikToplam.zaman;

                }
                oncelikToplam = oncelikToplam.next;

            }
            dlmSonuc.addElement("Oncelik Toplam Sure : " + toplamOncelik);
            lstSonuc.setModel(dlmSonuc);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Hatali giris yaptiniz ,hataniz : " + e);
            //System.out.println("Hatali giris yaptiniz , hataniz : " + e );

        }


    }//GEN-LAST:event_btnOncelikToplamSureActionPerformed

    private void btnFaturaGirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFaturaGirActionPerformed
        // TODO add your handling code here:
        dlmSonuc.removeAllElements();
        try {
            Node faturaGir = queueList.front;
            while (faturaGir != null) {
                if (faturaGir.faturaTipi.equals(txtFaturaGir.getText())) {

                    dlmSonuc.addElement(faturaGir.adSoyad + "-" + faturaGir.faturaTipi + "-" + faturaGir.faturaMiktari + "-" + faturaGir.oncelik + "-" + faturaGir.zaman);
                }
                faturaGir = faturaGir.next;
            }
            lstSonuc.setModel(dlmSonuc);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Hatali giris yaptiniz ,hataniz : " + e);
            //System.out.println("Hata : " + n.getMessage());
        }


    }//GEN-LAST:event_btnFaturaGirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KuyrukEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KuyrukEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDosyaOku;
    private javax.swing.JButton btnFaturaGir;
    private javax.swing.JButton btnMusteriCagir;
    private javax.swing.JButton btnOncelikGir;
    private javax.swing.JButton btnOncelikToplamSure;
    private javax.swing.JButton btnToplamFatura;
    private javax.swing.JButton btnToplamSure;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblMusteriler;
    private javax.swing.JList<String> listKuyruktanCikanlar;
    private javax.swing.JList<String> listMusteriler;
    private javax.swing.JList<String> lstSonuc;
    private javax.swing.JTextField txtFaturaGir;
    private javax.swing.JTextField txtOncelikGir;
    private javax.swing.JTextField txtOncelikToplamSure;
    // End of variables declaration//GEN-END:variables
}
